name: Vercel deployment prueba 1
  on:
    push:
      - main
jobs:
  test:
    name: Testing of the code
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm i
      - name: run tests
        run: npm run test
  vercel:
    needs: [test]
    name: "Deploy front-end" 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org/

      - name: "Deploy to Vercel"
        run: npx vercel --token ${CI_CD_VERCEL} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.CI_CD_VERCEL }}
          VERCEL_PROJECT_ID: ${{ secrets.CI_CD_VERCELTOKENPROJECT }}
          VERCEL_ORG_ID: ${{ secrets.CI_CD_VERCELORGID }}