name: Vercel deployment prueba 1
  on:
    push:
      - main
jobs:
  test:
    name: Testing of the code
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm i
      - name: run tests
        run: npm run test
      